import streamlit as st
import plotly.express as px
import sys
import os
import pandas as pd

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from modules.gee_utils import extract_satellite_data
from modules.data_processor import generate_mock_cpcb_data

st.set_page_config(page_title="Data Explorer", page_icon="📂", layout="wide")

st.title("📂 Environmental Data Explorer")
st.markdown("Visualize raw satellite and meteorological grids over India.")

# Mock/Live mode indicator
mode_indicator = "🧪 Mock Mode" if st.session_state.get('use_mock_data', True) else "🛰️ Live GEE Mode"
st.markdown(f"**Data Mode:** {mode_indicator}")

# CPCB Data Upload Section
st.markdown("### 📤 CPCB Ground Station Data")
uploaded_file = st.file_uploader("Upload CPCB CSV data (optional)", type=['csv'], help="Upload real CPCB data with columns: station_name, latitude, longitude, date, PM2.5, PM10, NO2, SO2, CO, O3, AQI")

if uploaded_file:
    try:
        cpcb_df = pd.read_csv(uploaded_file)
        st.success(f"Loaded {len(cpcb_df)} records from {cpcb_df['station_name'].nunique()} stations")
        st.dataframe(cpcb_df.head(10), use_container_width=True)
        if st.checkbox("Show data statistics"):
            st.write(cpcb_df.describe())
    except Exception as e:
        st.error(f"Error loading CSV: {e}")
else:
    start_date = st.session_state.get('start_date', '2024-01-01')
    end_date = st.session_state.get('end_date', '2024-12-31')
    mock_cpcb = generate_mock_cpcb_data(start_date, end_date)
    st.info(f"Using mock CPCB data: {len(mock_cpcb)} records across {mock_cpcb['station_name'].nunique()} stations")
    if st.checkbox("Preview mock CPCB data"):
        st.dataframe(mock_cpcb.head(10), use_container_width=True)

@st.cache_data
def load_data(start_date, end_date):
    # Load synthetic data
    return extract_satellite_data(
        collection_id=None, bands=None,
        start_date=start_date, end_date=end_date,
        spatial_resolution=0.5
    )

start_date = st.session_state.get('start_date', '2024-01-01')
end_date = st.session_state.get('end_date', '2024-12-31')

with st.spinner("Loading geospatial grids..."):
    data = load_data(start_date, end_date)

variable = st.selectbox(
    "Select Variable to Visualize",
    ["HCHO", "NO2", "SO2", "CO", "O3", "temp", "wind_u", "wind_v", "blh"]
)

grid = data[variable]
lon = data['lon']
lat = data['lat']

st.markdown(f"### {variable} Grid")
fig = px.imshow(
    grid, 
    x=lon[0, :], 
    y=lat[:, 0],
    color_continuous_scale='Viridis',
    origin="lower",
    labels={'x': 'Longitude', 'y': 'Latitude', 'color': variable},
    aspect="auto"
)
fig.update_layout(
    height=600,
    margin=dict(l=60, r=30, t=60, b=60),
    paper_bgcolor='#ffffff',
    plot_bgcolor='#f8f9fa',
    title=dict(
        text=f'{variable} Concentration',
        font=dict(size=18, color='#1a1a2e')
    ),
    xaxis=dict(
        title_font=dict(size=14, color='#1a1a2e'),
        tickfont=dict(size=12, color='#1a1a2e')
    ),
    yaxis=dict(
        title_font=dict(size=14, color='#1a1a2e'),
        tickfont=dict(size=12, color='#1a1a2e')
    ),
    coloraxis_colorbar=dict(
        title_font=dict(size=14, color='#1a1a2e'),
        tickfont=dict(size=12, color='#1a1a2e')
    )
)
st.plotly_chart(fig, use_container_width=True, config={'displayModeBar': True, 'responsive': True})

st.info("Note: The data shown is currently generated by the Synthetic Geospatial Data Generator.")